FROM node:24-alpine3.22 as builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build


FROM node:24-alpine3.22 as runner

WORKDIR /app

COPY package*.json ./

RUN npm install --omit=dev

COPY --from=builder /app/build ./build

CMD ["node", "build/index.js"]