FROM node:24-alpine3.22 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate --config src/prisma.config.ts

RUN npm run build


FROM node:24-alpine3.22 AS runner

WORKDIR /app

COPY package*.json ./

RUN npm install --omit=dev

COPY --from=builder /app/build ./build

CMD ["node", "build/index.js"]